name: FSackur
url: http://fsackur.github.io
description: $Blog | Out-World

permalink: /:year/:month/:day/:title/
paginate: 10

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
